# Generated by Django 4.1 on 2023-11-10 04:50

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=50)),
                ('product_description', models.CharField(blank=True, max_length=100)),
                ('product_cost_price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20000)])),
                ('product_remarks', models.TextField(blank=True, verbose_name='Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('vendor_name', models.CharField(max_length=20, unique=True)),
                ('vendor_poc', models.CharField(max_length=40)),
                ('vendor_gstin', models.CharField(max_length=20, unique=True)),
                ('vendor_address', models.TextField(blank=True, verbose_name='Official Address')),
                ('vendor_phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Primary Contact Number')),
                ('vendor_phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Secondary Contact Number')),
            ],
        ),
    ]
