# Generated by Django 4.1 on 2023-11-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_id',
            field=models.ManyToManyField(to='billingapp.vendor'),
        ),
    ]
