# Generated by Django 4.1 on 2023-11-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0002_product_vendor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor_id',
            new_name='vendors',
        ),
    ]
