# Generated by Django 4.1 on 2023-11-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0003_rename_vendor_id_product_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendors',
            field=models.ManyToManyField(related_name='products', to='billingapp.vendor'),
        ),
    ]
