# Generated by Django 4.1 on 2023-11-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0004_alter_product_vendors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventories', serialize=False, to='billingapp.product')),
                ('inv_available', models.IntegerField(blank=True)),
                ('inv_allocated', models.IntegerField(blank=True)),
            ],
        ),
    ]
