# Generated by Django 4.1 on 2023-11-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0005_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_id',
            field=models.AutoField(default='11', editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='billingapp.product'),
        ),
    ]
