# Generated by Django 4.1 on 2023-11-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0006_inventory_inventory_id_alter_inventory_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product_id',
            new_name='product',
        ),
    ]
