# Generated by Django 4.1 on 2023-11-18 14:59

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billingapp', '0007_rename_product_id_inventory_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=255, unique=True)),
                ('customer_poc', models.CharField(max_length=40)),
                ('customer_gst', models.CharField(max_length=20, unique=True)),
                ('customer_address', models.TextField(blank=True, verbose_name='Official Address')),
                ('customer_pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter Valid Pincode!', regex='^[1-9]{1}[0-9]{2}\\s{0,1}[0-9]{3}$')])),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Primary Contact Number')),
                ('customer_phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Secondary Contact Number')),
            ],
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_gstin',
            new_name='vendor_gst',
        ),
        migrations.AddField(
            model_name='product',
            name='product_gst_percentage',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='product_hsn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_unit',
            field=models.CharField(default='Nos', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_pincode',
            field=models.CharField(default='600006', max_length=6, validators=[django.core.validators.RegexValidator(message='Enter Valid Pincode!', regex='^[1-9]{1}[0-9]{2}\\s{0,1}[0-9]{3}$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_json', models.TextField()),
                ('inventory_reflected', models.BooleanField(default=True)),
                ('books_reflected', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billingapp.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('change', models.IntegerField(default=0)),
                ('change_type', models.IntegerField(choices=[(0, 'Other'), (1, 'Purchase'), (2, 'Production'), (4, 'Sales')], default=0)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('associated_invoice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billingapp.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billingapp.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('change_type', models.IntegerField(choices=[(0, 'Paid'), (1, 'Purchased Items'), (2, 'Sold Items'), (4, 'Other')], default=0)),
                ('change', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('associated_invoice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billingapp.invoice')),
                ('parent_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billingapp.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billingapp.customer'),
        ),
        migrations.AddField(
            model_name='book',
            name='last_log',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billingapp.booklog'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
