# Generated by Django 4.1 on 2023-11-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0008_book_customer_rename_vendor_gstin_vendor_vendor_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billingapp.customer'),
        ),
    ]
